### ISSUE TITLE
Distribution of 1.3.5

### ISSUE THREAD

**Issue by vomikan** [moneymanagerex/moneymanagerex#2393]
- [x] #2392 Transaction colour
- [ ] #1664 Custom items in checking panel
- [x] #2387 mmexini.db3
- [ ] Home page customization #2386
- [x] Temp folder deprecated #2394
- [x] #2231 Export to JSON
- [x] Graph scaling #2395
- [x] #2040 Notes field append
